Started implementing support for the AIM TOC protocol. First commit of the stuff.

diff --git a/misc/cicqsync b/misc/cicqsync
--- a/misc/cicqsync
+++ b/misc/cicqsync
@@ -6,13 +6,13 @@
 #
 # by Konstantin Klyagin <konst@konst.org.ua>
 #
-# $Id: cicqsync,v 1.14 2002/01/21 10:50:40 konst Exp $
+# $Id: cicqsync,v 1.15 2002/03/14 11:53:28 konst Exp $
 #
 
 CROOT=":pserver:anonymous@cvs.konst.org.ua:/home/konst/cvs/root"
 
 PROG="centericq"
-MODULES="libyahoo libmsn libicq2000 kktoolbox/kkconsui kktoolbox/kksystr kktoolbox/kkstrtext"
+MODULES="libyahoo libmsn libicq2000 kktoolbox/kkconsui kktoolbox/kksystr kktoolbox/kkstrtext firetalk"
 MAKEUPDATE="s@/home/konst/devel/kktoolbox@\$(top_srcdir)@g;s@/home/konst/devel/libyahoo@\$(top_srcdir)/libyahoo@g;s@/home/konst/devel/libmsn@\$(top_srcdir)/libmsn@;s@/home/konst/devel/libicq2000@\$(top_srcdir)/libicq2000@g"
 MONOLITE="0"
 
@@ -20,6 +20,16 @@ RETVAL=0
 CVS="cvs -z9 -d $CROOT"
 
 moduledir=""
+
+checkutils() {
+    for i in automake autoconf gettextize; do
+	r=`which $i 2>&1`
+	if test ! -f "$r"; then
+	    echo "error: you must have $i installed to be able to use $0"
+	    exit 1
+	fi
+    done
+}
 
 preparedirs() {
     if test ! -d ${DEST}; then
@@ -190,6 +200,8 @@ make install
 if test $# -lt 2; then
     usage
 else
+    checkutils
+
     if test ! -d $2; then
 	echo "the location you specified does not exist: $2"
 	exit
